### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Can't load C:\Users\...\skija.dll

### ISSUE THREAD

**Issue by istinnstudio** [jfree/skijagraphics2d#8]
Great project!
I have tried to convert some java2D graphics directly via skija with SkijaGraphics2D, but the external dll cannot be loaded even if extracted OK in the temp directory. 
I have compiled SkijaGraphics2D with ant by manually resolving dependencies, slf4j-api, slf4j-simple, types and skija from humbleui and skija at the maven version 0.98.1 and the latest 0.100.  Same results for both. 

COMPILE SkijaGraphics2D (windows skija version):
This line of code in netbeans shows an error:

SkijaGraphics2D.java
```
            // needs clojure library dependency ????????????
            this.canvas.drawRect(Rect.makeXYWH((float) r.getX(), (float) r.getY(), (float) r.getWidth(), (float) r.getHeight()), this.skijaPaint);
```
then after a bit of search I have seen that it needs clojure library also. So after resolving closure depedancy compiles OK.

Then after loading all libs in order to use them, in the sense of what I see I the test -->

```
           // Test SkijaGraphics2D...
            this.g2 = new SkijaGraphics2D(10, 20);
```

RUNTIME:
I get this error even before parsing any code to the next level, stops at loading the external dll, the skija.dll and icudtl.dat file is there,
```

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Can't load C:\Users\...\AppData\Local\Temp\skija_0.98.1\skija.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1793)
	at java.base/java.lang.System.load(System.java:672)
	at io.github.humbleui.skija.impl.Library.load(Library.java:73)
	at io.github.humbleui.skija.impl.Library.staticLoad(Library.java:47)
	at io.github.humbleui.skija.Surface.<clinit>(Surface.java:10)
	at org.jfree.skija.SkijaGraphics2D.<init>(SkijaGraphics2D.java:214)
```

**Comment by istinnstudio** [comment]
a related reading could be : https://javarevisited.blogspot.com/2012/03/javalangunsatisfiedlinkerror-no-dll-in.html#axzz7MiPsfd6P
but this "path" stuff in java is a mess. We might need to reconsider the loading class and point to a more predictable directory other than the temp.
